apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: memory-utilization
spec:
  args:
    - name: namespace
    - name: stable-hash
    - name: canary-hash
    - name: prometheus-port
    - name: memory-utilization-limit-perc
      value: "90"
    - name: initial-delay
      value: "1m"
    - name: count
      value: "10"
    - name: interval
      value: "60s"
    - name: failure-limit
      value: "1"
    - name: inconclusive-limit
      value: "1"
  metrics:
    - name: memory-utilization
      successCondition: result[0] <= {{args.memory-utilization-limit-perc}}
      initialDelay: "{{args.initial-delay}}"
      interval: "{{args.interval}}"
      count: "{{args.count}}"
      failureLimit: "{{args.failure-limit}}"
      inconclusiveLimit: "{{args.inconclusive-limit}}"
      provider:
        prometheus:
          address: "http://prometheus.metrics-ns.svc.cluster.local:{{args.prometheus-port}}"
          query: |-
            (quantile(0.5, quantile_over_time(0.5, namespace_pod_memory_utilization{namespace="{{args.namespace}}", pod=~".*-{{args.canary-hash}}-.*"}[11m])))
