apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: request-latency
spec:
  args:
    - name: namespace
    - name: stable-hash
    - name: canary-hash
    - name: prometheus-port
    - name: request-latency-limit-msec
    - name: initial-delay
      value: "1m"
    - name: count
      value: "10"
    - name: interval
      value: "60s"
    - name: failure-limit
      value: "1"
    - name: inconclusive-limit
      value: "1"
  metrics:
    - name: request-latency
      successCondition: result[0] < {{args.request-latency-limit-msec}}
      initialDelay: "{{args.initial-delay}}"
      interval: "{{args.interval}}"
      count: "{{args.count}}"
      failureLimit: "{{args.failure-limit}}"
      inconclusiveLimit: "{{args.inconclusive-limit}}"
      provider:
        prometheus:
          address: "http://prometheus.metrics-ns.svc.cluster.local:{{args.prometheus-port}}"
          query: |-
            (quantile(0.95, quantile_over_time(0.95, namespace_pod_http_server_requests_latency{namespace="{{args.namespace}}", rollouts_pod_template_hash="{{args.canary-hash}}"}[11m]))*1000)
