apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: namespace
    - name: stable-hash
    - name: canary-hash
    - name: prometheus-port
    - name: success-rate-min-percentage
    - name: initial-delay
      value: "1m"
    - name: count
      value: "10"
    - name: interval
      value: "60s"
    - name: failure-limit
      value: "1"
    - name: inconclusive-limit
      value: "1"
  metrics:
    - name: success-rate
      successCondition: result[0] >= {{args.success-rate-min-percentage}}
      initialDelay: "{{args.initial-delay}}"
      interval: "{{args.interval}}"
      count: "{{args.count}}"
      failureLimit: "{{args.failure-limit}}"
      inconclusiveLimit: "{{args.inconclusive-limit}}"
      provider:
        prometheus:
          address: "http://prometheus.metrics-ns.svc.cluster.local:{{args.prometheus-port}}"
          query: |-
            (sum(sum_over_time(namespace_pod_http_server_requests_2xx{namespace="{{args.namespace}}", rollouts_pod_template_hash="{{args.canary-hash}}"}[11m]))
            /
            sum(sum_over_time(namespace_pod_http_server_requests_count{namespace="{{args.namespace}}", rollouts_pod_template_hash="{{args.canary-hash}}"}[11m]))) * 100